### ISSUE TITLE
Support one_file_per_schema for model_props_strategy

### ISSUE THREAD

**Issue by joellabes** [datacoves/dbt-coves#10]
We create one file per schema, as opposed to per table. Currently I am manually merging the table-specific data into a single file, but it would be nice for this to happen automatically. 

Given that the strategy config exists at all, I assume this is already under consideration for the future!

**Comment by ssassi** [comment]
That's right @joellabes. We already considered different strategies to create model props.
Thanks for pointing it out.

**Comment by noel** [comment]
@joellabes this was done now there are 3 options:
- One file for the whole project
- One file per schema
- One file per staging model (combined as it used to be)

**Comment by joellabes** [comment]
Awesome! Thank you for letting me know 🌟

**Comment by noel** [comment]
I just realized I didnt explain this well, basically in the config file you can define where the objects are created and this will achieve what you want.
Stay tuned for a video

**Comment by bbrewington** [comment]
heads up, I'm seeing this in the output of `dbt-coves generate properties -h`:

```text
--model-props-strategy MODEL_PROPS_STRATEGY
                        Strategy for model properties file generation, i.e. 'one_file_per_model'
```

...but there's no explanation in the README.md - basically, I just need to know which values are available for the strategy, and what each of them do

here's where above command line stuff is defined:

https://github.com/datacoves/dbt-coves/blob/f14072d664ddf14c54f7fbb5b26c965b67ca19f2/dbt_coves/tasks/generate/properties.py#L40-L45

**Comment by BAntonellini** [comment]
> heads up, I'm seeing this in the output of `dbt-coves generate properties -h`:
> 
> ```
> --model-props-strategy MODEL_PROPS_STRATEGY
>                         Strategy for model properties file generation, i.e. 'one_file_per_model'
> ```
> 
> ...but there's no explanation in the README.md - basically, I just need to know which values are available for the strategy, and what each of them do
> 
> here's where above command line stuff is defined:
> 
> https://github.com/datacoves/dbt-coves/blob/f14072d664ddf14c54f7fbb5b26c965b67ca19f2/dbt_coves/tasks/generate/properties.py#L40-L45

`--model-props-strategy` was deprecated in favor of `--destination` usage

We forgot to remove the help message from the command parser, what resulted in the argument being present in `-h` help message. Thank you for pointing it out.

`generate properties` aims to generate and update the properties file for a given dbt model file, so with `--destination` you can place the resultant YML files wherever you need them. https://github.com/datacoves/dbt-coves#properties-generation-arguments

flags `{{model_folder_path}}` and `{{model_file_name}}` refer to the SQL containing folder and filename respectively. For example:

`--destination {{model_folder_path}}/{{model_file_name}}.yml` will create one YML per SQL file at the same level
`--destination properties/{{model_file_name}}.yml` will create one YML per SQL file in `properties` folder
`--destination {{model_folder_path}}/properties.yml` will create a single YML property file at the same level of selected models

and so on...
