### ISSUE TITLE
Installing dbt-coves downgraded my dbt installation (with specified adapter) to 0.18.2 [BUG]

### ISSUE THREAD

**Issue by joellabes** [datacoves/dbt-coves#11]
**Describe the bug**
I had dbt-redshift installed in a pipenv, and when I installed dbt-coves it looks like it installed dbt@0.18.2 (without a specific dbt adapter specified)

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new pipenv 
2. pipenv install dbt-redshift 
3. Run dbt --version, note that plugins postgres and redshift are installed at 0.19.2
3. pipenv install dbt-coves
4. Run dbt --version, note that all 4 core plugins (the two above plus snowflake and BQ) are installed at 0.18.2
5. Run pipenv update dbt-redshift
6. Run dbt --version and get 

```
installed version: 0.19.2
   latest version: 0.19.2

Up to date!

Plugins:
  - bigquery: 0.18.2
  - postgres: 0.19.2
  - redshift: 0.19.2
  - snowflake: 0.18.2
```
8. Note that BQ and SF are still 0.18.2 but PG and RS are 0.19.2

**Expected behaviour**
Installing dbt-coves shouldn't clobber an existing dbt install which has specified a specific adapter

**Desktop (please complete the following information):**
Windows 10 
Python 3.8
dbt-coves v0.19.2-a.10

**Comment by ktnsh24** [comment]
Hello @joellabes,

Could you please try with new dbt version 0.20.0 and then let us know?

In my case, It is now downgrading the version of BG and SF with new version. Also, before when I installed dbt-coves for dbt 0.19.2, It didn't downgrade the version. 

However, I was using mac, with python 3.8, and dbt-coves v0.19.2-a.10. 

Please let us know if it is creating the same issue with 0.20.0 in your machine.

**Comment by ssassi** [comment]
Could not reproduce the bug.
