### ISSUE TITLE
[BUG] Table not found on BigQuery datastet

### ISSUE THREAD

**Issue by edbizarro** [datacoves/dbt-coves#12]
**Describe the bug**
Table not found on BigQuery datastet

**To Reproduce**
dbt-coves generate source

**Expected behaviour**
Generate files from source tables

**Console Log/Tracebacks**

```
Which schemas would you like to inspect? [RAW_RTB_HOUSE_GSHEETS]
No tables/views found in RAW_RTB_HOUSE_GSHEETS schema.
```

**Desktop (please complete the following information):**

- OS: Linux

**Additional context**

Besides console info are all on uppercase, all my sources datasets and tables are lowercase

**Comment by ssassi** [comment]
Isn't this fixed already @SantiMenendez19?

**Comment by ssassi** [comment]
This was fixed.
