### ISSUE TITLE
[BUG] Jinja Templating breaks on multiple references of `{{ schema}}`

### ISSUE THREAD

**Issue by mattppal** [datacoves/dbt-coves#269]
**Describe the bug**
When defining `sources_destination`, `models_destination`, etc in `.dbt_coves/config.yml`, the first reference to `schema` is unable to be altered, while following sources can be

**To Reproduce**

Steps to reproduce the behaviour:

Define:

`models_destination: "models/staging/{{ schema }}/{{ schema | replace('raw','stg')  }}__{{ relation }}.sql"`

dbt-coves functions as expected, but with

`models_destination: "models/staging/{{ schema | replace('raw','') }}/{{ schema | replace('raw','stg')  }}__{{ relation }}.sql"`

the first reference to `schema` returns a blank string.

**Expected behaviour**

I would expect referencing the same variable in the same line to function identically.

**Comment by BAntonellini** [comment]
@mattppal we've just implemented the fix, and `dbt-coves 1.3.0a8` was published on PyPI

Thank you for your contribution!

**Comment by mattppal** [comment]
Wow thanks for the quick fix!
