### ISSUE TITLE
[BUG] Generate Sources in BigQuery with same table name (different cases)

### ISSUE THREAD

**Issue by SantiMenendez19** [datacoves/dbt-coves#274]
**Describe the bug**
When i use dbt-coves generate sources in a dbt project with BigQuery and i create models for 2 tables with the same name but different cases, the function only returns one of the models and overwrites the other.

**To Reproduce**
Steps to reproduce the behaviour:

1. Create in BigQuery two tables with the same name, one with lowercase and the other with uppercase.
2. Execute dbt-coves generate sources for the BigQuery dbt project
3. In the CLI, select both tables that you created
4. dbt-coves create the models for the two tables, but only returns one of the models and the other overwrites.

**Console Log/Tracebacks**
![image](https://user-images.githubusercontent.com/42306463/205929885-66dacd9b-f40b-4b1c-816e-6262dd3ded87.png)
![image](https://user-images.githubusercontent.com/42306463/205929925-d74e6e2b-3347-4d32-80e4-175d0de431a4.png)

- OS: Ubuntu
- Version: dbt-coves v1.3.0-alpha.8

**Comment by BAntonellini** [comment]
Fixed in PR #309

Now you can't select two tables with the same name on the same schema
