### ISSUE TITLE
[BUG] ❌ 'bool' object has no attribute 'parent' after running `dbt-coves setup all`

### ISSUE THREAD

**Issue by jaredx435k2d0** [datacoves/dbt-coves#303]
**Describe the bug**

After running `dbt-coves setup all` and going through the prompts, I get:

> dbt init                                                               SUCCESS ✔
> 
> 
> ❌ 'bool' object has no attribute 'parent'

**To Reproduce**
Steps to reproduce the behaviour:

1. Run `dbt-coves setup all`

**Expected behaviour**
To not get the `> ❌ 'bool' object has no attribute 'parent'` output

**Desktop (please complete the following information):**

- OS: macOS 13.2 (22D49)
- Python: 3.10.9
- output of `pip freeze`:
agate==1.6.3
asn1crypto==1.5.1
attrs==22.2.0
Babel==2.11.0
bump2version==1.0.1
bumpversion==0.6.0
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==2.1.1
click==8.1.3
colorama==0.4.5
commonmark==0.9.1
cryptography==36.0.2
dbt-core==1.3.2
dbt-coves==1.3.0a20
dbt-extractor==0.4.1
dbt-snowflake==1.3.0
filelock==3.9.0
future==0.18.3
hologram==0.0.15
idna==3.4
importlib-metadata==6.0.0
isodate==0.6.1
jaraco.classes==3.2.3
Jinja2==3.1.2
jsonschema==3.2.0
keyring==23.13.1
leather==0.3.4
Logbook==1.5.3
luddite==1.0.2
MarkupSafe==2.1.2
mashumaro==3.0.4
minimal-snowplow-tracker==0.0.2
more-itertools==9.0.0
msgpack==1.0.4
networkx==2.8.8
oscrypto==1.3.0
packaging==21.3
parsedatetime==2.4
pathspec==0.9.0
pretty-errors==1.2.25
prompt-toolkit==3.0.36
pycparser==2.21
pycryptodomex==3.16.0
pydantic==1.10.4
pyfiglet==0.8.post1
Pygments==2.14.0
PyJWT==2.6.0
pyOpenSSL==22.0.0
pyparsing==3.0.9
pyrsistent==0.19.3
python-dateutil==2.8.2
python-slugify==7.0.0
pytimeparse==1.1.8
pytz==2022.7.1
PyYAML==6.0
questionary==1.10.0
requests==2.28.2
rich==12.6.0
six==1.16.0
snowflake-connector-python==2.7.12
sqlparse==0.4.3
text-unidecode==1.3
typing_extensions==4.4.0
urllib3==1.26.14
wcwidth==0.2.6
Werkzeug==2.2.2
yamlloader==1.2.2
zipp==3.11.0

**Comment by noel** [comment]
Curious, did the setup actually succeed?  e.g. if you do `dbt debug` is it successful?

**Comment by jaredx435k2d0** [comment]
Yeah, `dbt debug` returns `All checks passed!`

**Comment by BAntonellini** [comment]
@jaredx435k2d0 this has been fixed in [PR #308](https://github.com/datacoves/dbt-coves/pull/308)
