### ISSUE TITLE
Support for dbt 1.5

### ISSUE THREAD

**Issue by dstollie** [datacoves/dbt-coves#381]
**Is your feature request related to a problem? Please describe.**
When I was trying to install this package I got an error since I the dbt-project I was using was already on `1.5`. Since this version of dbt is the default now, I was wondering when this package could be bumped to that version? We are using poetry and poetry is pretty strict when it comes to versioning.

**Describe the solution you'd like**
Bump the supported version of dbt-coves to 1.5

**Comment by BAntonellini** [comment]
@dstollie thank you for contributing.

We've released `dbt-coves 1.5.X` extending support to dbt-core 1.5

https://pypi.org/project/dbt-coves/
