### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by amihaygil** [datacoves/dbt-coves#54]
dbt-coves v0.20.0-a.3              dbt v0.20.2

Can't instantiate abstract class GenerateTask with abstract methods run
**To Reproduce**
Steps to reproduce the behaviour:

1. Run command "dbt-coves generate --profile cloud"
2. etc.

I assume because dbt v0.20.2 is not supported. 

I've installed dbt-coves in a fresh venv. I guess it might be good idea to constraint the dependencies  for support version to help `getting started` more easir

**Comment by mprunell** [comment]
Actually "dbt-coves generate sources --profile cloud" works. The "sources" subcommand is missing, but the error message is misleading.

**Comment by mprunell** [comment]
Error message to be fixed in #149
