### ISSUE TITLE
Restrict generate sources to output yml files only

### ISSUE THREAD

**Issue by kon-mal** [datacoves/dbt-coves#6]
**Is your feature request related to a problem? Please describe.**
Generating full .yml files (model name, list of columns, empty description fields) for every model in a dbt project - thorough documentation.

**Describe the solution you'd like**
If the current generate sources function had a flag that disables .sql files creation / or `yml-only` flag, it would achieve exactly that. Although it's set up for sources specifically, if you provide your analytics schema in the .dbt_coves.yml, it will create the yml definitions for all of the dbt models in a project. 

**Describe alternatives you've considered**
As an alternative I had a wrapper python function that captured terminal output of this function https://github.com/dbt-labs/dbt-codegen/blob/0.3.2/macros/generate_model_yaml.sql for each model and created the ymls.

**Additional context**
The generate sources function is extremely useful in creating staging models for a dbt project. It seems, however, that it could be easily extended to help with thorough documentation of all models within a dbt project. Ideally, it wouldn't then put the "sources" part at the top of the file, but that's much easier to get rid of than creating all of the ymls from scratch!

**Comment by ssassi** [comment]
Nice idea @kon-mal.
I would suggest then creating another variant of the `generate` subcommand, i.e. `dbt-coves generate models`.
Instead of reading the DB schema, I'd suggest reading models information from the [dbt manifest](https://docs.getdbt.com/reference/artifacts/manifest-json).
The tool could list the models so the user selects which ones to generate.

**Comment by noel** [comment]
@kon-mal `generate properties` now exists
