### ISSUE TITLE
Add dbt-coves generate properties

### ISSUE THREAD

**Issue by ciejer** [datacoves/dbt-coves#92]
**Is your feature request related to a problem? Please describe.**
It can be painful to create .yml files for dbt models; the behaviour of `dbt-coves generate properties` would be helpful for models also.

**Describe the solution you'd like**
Addition of command `dbt-coves generate properties`, which searches the manifest for models without a patch_path; presents an interface for selection like `dbt-coves generate sources` does, and creates a templated .yml file with all columns listed for selected models.

**Describe alternatives you've considered**
dbt-sugar contains this functionality, as does codegen. However, using multiple separate tools to do essentially the same thing (from the user perspective) is not ideal, as it requires the user to remember which tool does which specific use case.

**Comment by ssassi** [comment]
Nice feature. We could use https://github.com/Dashlane/dbt-invoke as inspiration.

**Comment by noel** [comment]
Done and with the option to define a template for the generated model
